"""add stored_filename to conversion_jobs

Revision ID: 5b67918a4cf3
Revises: f306f6d83ac4
Create Date: 2026-06-11 14:20:43.779735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b67918a4cf3'
down_revision = 'f306f6d83ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stored_filename', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.drop_column('stored_filename')

    # ### end Alembic commands ###
