"""upload_limit to users has been added

Revision ID: db8c1b75f7fc
Revises: f0b8b9e49b8a
Create Date: 2026-06-12 15:05:59.808532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8c1b75f7fc'
down_revision = 'f0b8b9e49b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.alter_column('layout_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_conversion_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversion_jobs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('upload_limit')

    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversion_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversion_jobs_status'))
        batch_op.alter_column('layout_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
