"""add records_processed

Revision ID: f0b8b9e49b8a
Revises: 1b89657d7be2
Create Date: 2026-06-11 15:18:16.624695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b8b9e49b8a'
down_revision = '1b89657d7be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('records_processed', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversion_jobs', schema=None) as batch_op:
        batch_op.drop_column('records_processed')

    # ### end Alembic commands ###
