JOB_PENDING = "PENDENTE"
JOB_PROCESSING = "PROCESSANDO"
JOB_COMPLETED = "CONCLUIDO"
JOB_ERROR = "ERRO"

LAYOUT_CLIENTES = "CLIENTES"
LAYOUT_PRODUTOS = "PRODUTOS"
LAYOUT_ESTOQUE = "ESTOQUE"
MAX_PENDING_UPLOADS = 5